### ISSUE TITLE
Chokes on "npm-style" imports

### ISSUE THREAD

**Issue by vemv** [gfredericks/how-to-ns#11]
Different from https://github.com/gfredericks/how-to-ns/issues/9

Strings are accepted in cljs for requiring npm stuff:

```clojure
   ["moment" :as moment]
   ["moment/locale/es"]
```

Processing that will cause a `java.lang.ClassCastException: clojure.lang.Symbol cannot be cast to java.lang.String`.

**Comment by gfredericks** [comment]
wow, I had no idea

ideally support for this would only be applied to cljs or the right parts of cljc, but I can imagine that being difficult to implement

**Comment by gfredericks** [comment]
I suppose "clj-jvm programmers might accidentally use strings in their requires!" isn't a big deal since they'll find out about it via compile errors anyhow, so supporting it everywhere is fine

**Comment by vemv** [comment]
> I suppose "clj-jvm programmers might accidentally use strings in their requires!" isn't a big deal since they'll find out about it via compile errors anyhow, so supporting it everywhere is fine

Agreed! Shall I PR?

(also, gentle reminder about the open one)

**Comment by gfredericks** [comment]
yes, PR would be great

w.r.t. the gentile reminder, I've not lost track of it (and won't), but it may take me a week or so.

vetting an idea is a lot easier than reviewing & evaluating a PR

thanks for the contributions, I appreciate it!
