### ISSUE TITLE
Ability to use it with deps

### ISSUE THREAD

**Issue by velios** [gfredericks/how-to-ns#20]

**Comment by vemv** [comment]
The com.gfredericks.how-to-ns and com.gfredericks.how-to-ns.main namespaces are available in the https://clojars.org/com.gfredericks/how-to-ns artifact

**Comment by velios** [comment]
@vemv Yes, thank you very much for the reminder. I will try to implement this myself as soon as I have time and understanding of how to do it.

**Comment by velios** [comment]
It's possible now, thanks for your time!
