### ISSUE TITLE
:require-macros is stripped

### ISSUE THREAD

**Issue by vemv** [gfredericks/how-to-ns#4]
Hi! Great library; pleasure to see it working in a cljs project as well.

:require-macros is dropped though, similarly to what happened in https://github.com/gfredericks/how-to-ns/issues/2 .

Could you give it a 👀?

Cheers - Victor

**Comment by gfredericks** [comment]
Thanks for the report -- I'll give it a look tomorrow.

**Comment by vemv** [comment]
Ace!

I see back in May you committed `0.1.7-SNAPSHOT`, but that one does not appear in https://clojars.org/com.gfredericks/how-to-ns .

Mind to push?

**Comment by gfredericks** [comment]
Oh, the snapshots aren't intended to be published.

I was going to make a proper release out of it, but had to wait till now.

I would've left the ticket open so as not to confuse, but github auto-closes them just based on the commit message :).

I just released `0.1.7`.

**Comment by vemv** [comment]
> Oh, the snapshots aren't intended to be published.

You (or I) might be confused! For example I see https://clojars.org/cider/cider-nrepl releases its snapshot versions.

Anyway, I tested out 0.1.7 and it worked perfectly in our large cljs project. Kudos!

**Comment by gfredericks** [comment]
Oh I only meant that my projects don't publish snapshots -- I just make real releases frequently enough that I don't need to.
