### ISSUE TITLE
Does not preserve attr-map

### ISSUE THREAD

**Issue by chairmank** [gfredericks/how-to-ns#6]
It loses the map of attributes between the docstring and the namespace clauses.

If you don't already have a fix for this issue in development, I can provide a patch.

**Comment by gfredericks** [comment]
I agree this should be preserved.

Easy thing: use `(pr-str (into (sorted-map) attrs))` to print it on one line with sorted keys

Hard thing: use the reader to get the original formatting, and pass that through provided it meets some minimum requirements (nothing else on its lines, etc.)
