### ISSUE TITLE
Chokes on reader conditionals

### ISSUE THREAD

**Issue by vemv** [gfredericks/how-to-ns#9]
Hi there,

a ns form with reader conditionals will fail with the following:

```
Caused by: java.lang.RuntimeException: Conditional read not allowed
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.LispReader$ConditionalReader.checkConditionalAllowed(LispReader.java:1623)
...
```

That could be fixed by passing options in https://github.com/gfredericks/how-to-ns/blob/563fea7ea8bd8177bcf20a4dc6f643a7ec0209c1/how-to-ns/src/com/gfredericks/how_to_ns.clj#L230 instead of `{}`.

Maybe a complete solution would involve aligning the :clj and :cljs clauses, but for maybe now just avoiding failure would be quite an improvement.

WDYT?

Thanks - V

**Comment by gfredericks** [comment]
I'd definitely accept a PR that did this, probably also sorting the pairs before printing, unless the order is maintained by the reader.

**Comment by vemv** [comment]
Thanks for the reviewing/releasing!
